### ISSUE TITLE
Suggestion: Use eslint to enforce for editorconfig options

### ISSUE THREAD

**Issue by victorperin** [khaosdoctor/template-node-ts#1]
First of all, congratulations on this repo, this will help a lot of people to bootstrap typescript applications. 🎉 

So, you can use [eslint-plugin-editorconfig](https://github.com/phanect/eslint-plugin-editorconfig) to enforce the editorconfig options. This will also prevent duplications, like setting tabs in editorconfig but forgetting to change it in prettier, for example.

**Comment by khaosdoctor** [comment]
AWESOME IDEA I'll apply it right now! Thanks a lot!
